language: python

env:
  DATABASE_TESTING_URL="dbname='questionertest' host='127.0.0.1' port='5432' user='postgres' password=''"

python:
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls 


services:
  - postgresql

addons:
postgresql: "9.6"

before_script:

  - psql -c 'create database questioner;' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
 - pytest --cov app/tests/v2

after_success:
 - coveralls
 
