language: python

python:
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls 


services:
  - postgresql

before_script:
  - psql -c 'create database questioner;' -U postgres
  - psql -c 'create database questionertest;' -U postgres
  - psql -c "create user leewel with password 'root';" -U postgres

script:
 - export FLASK_ENV="testing"
 - export DATABASE_TESTING_URL="dbname=questionertest host=localhost port=5432 user=leewel password=root"
 - export DATABASE_URL="dbname=questioner host=localhost port=5432 user=postgres password=secret"
 - pytest --cov app/tests/v2

after_success:
 - coveralls
 
